version: '3.4'

services:
  itemrental-api:
    image: ${DOCKER_REGISTRY-}itemrentalapi
    build:
      context: .
      dockerfile: ItemRental.API/Dockerfile
    volumes:
      - image-data:/app/Images
    ports:
      - "8081:80"
      - "8082:443" 
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: zbdzJICdYcyrMHY
      MYSQL_USER: itemrental
      MYSQL_PASSWORD: PXmj9MxN74Kn3Iu
      MYSQL_DATABASE: itemrental
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ItemRental.Web/dist:/usr/share/nginx/html
    depends_on:
      - itemrental-api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=itemrental
      - PMA_PASSWORD=PXmj9MxN74Kn3Iu
      - PMA_PORT=3306
    ports:
      - "8083:80"
    depends_on:
      - mariadb
volumes:
  mysql-data:
  image-data:  